### PR TITLE
Refactor/exchange version upgrade

### PR DESCRIPTION
**Pull request by ganeshkumar1989**
MFRWW-719

### Requirements

* Upgrade from i18n translator to angular-translate

### Description of the Change

The upgrade to angular-translate has been done. All the dependencies - Sharepoint, Office and EmailPro have also been upgraded. 

**Link**
https://github.com/ovh-ux/ovh-module-exchange/pull/122
https://github.com/ovh-ux/ovh-module-emailpro/pull/76
https://github.com/ovh-ux/ovh-module-sharepoint/pull/33
https://github.com/ovh-ux/ovh-module-office/pull/34

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#4350.0 ✘  
* init
  * deps ✘

**Comment by ovh-cds** [comment]
CDS Report build#4360.0 ✘  
* init
  * deps ✘

**Comment by ovh-cds** [comment]
CDS Report build#4375.0 ✘  
* init
  * deps ✘

**Comment by ganeshkumar1989** [comment]
The eslint issues are fixed.

**Comment by ovh-cds** [comment]
CDS Report build#4378.0 ✘  
* init
  * deps ✘

**Comment by ovh-cds** [comment]
CDS Report build#4380.0 ✘  
* init
  * deps ✘

**Comment by JeremyDec** [comment]
@ganeshkumar1989 please resolve conflict

**Comment by ovh-cds** [comment]
CDS Report build#4390.0 ✘  
* init
  * deps ✘

**Comment by ovh-cds** [comment]
CDS Report build#4392.0 ✘  
* init
  * deps ✘

**Comment by ovh-cds** [comment]
CDS Report build#4403.0 ✘  
* init
  * deps ✘

**Pull request merged**
