### PR TITLE
Feat(*): remove obsolete manager v3 references

### PR DESCRIPTION
**Pull request by rfougier**
DO NOT MERGE !

### CODE REVIEW

**Comment by FredericEspiau** [comment]
When should we merge this then ?

**Comment by FredericEspiau** [comment]
When should we merge this then ?

**Comment by rfougier** [comment]
@FredericEspiau When we will sure that the managerV3 isn't used by some clients

**Comment by FredericEspiau** [comment]
@rfougier and when is that ? When do you get this piece of information ?

**Comment by rfougier** [comment]
@FredericEspiau i don't have any idea who can valid the v3 removing. I would like to know !
I made the PR to start the debate...

**Comment by FredericEspiau** [comment]
@rfougier you're a real jackanapes !

**Pull request closed without merging**
